services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    volumes:
      - mssql-data:/var/opt/mssql

  redis:
    image: redis:7.4-alpine
    restart: always
    container_name: redis-server
    command: redis-server --save 30 1 --loglevel warning --requirepass Password123
    volumes:
      - cache:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=Password123
    volumes:
      - rabbitmq-log:/var/log/rabbitmq

  api-gateway:
    build:
      context: .
      dockerfile: ./ApiGateway/Dockerfile
    container_name: api-gateway
    environment:
      - Jwt__Secret=Super Secret Key Super Secret Key Super Secret Key Super Secret Key
    ports:
      - "5000:8080"
    depends_on:
      - catalog-api
      - basket-api
      - identity-api
      - ordering-api

  catalog-api:
    build:
      context: .
      dockerfile: ./Catalog.API/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=database;Database=CatalogDb;User Id=sa;Password=Password123;TrustServerCertificate=True
      - ConnectionStrings__Redis=redis-server:6379,password=Password123
      - Jwt__Secret=Super Secret Key Super Secret Key Super Secret Key Super Secret Key
    depends_on:
      - database
      - redis

  basket-api:
    build:
      context: .
      dockerfile: ./Basket.API/Dockerfile
    environment:
      - ConnectionStrings__Redis=redis-server:6379,password=Password123
      - RabbitMqConfig__Host=rabbitmq
      - RabbitMqConfig__Username=admin
      - RabbitMqConfig__Password=Password123
      - Jwt__Secret=Super Secret Key Super Secret Key Super Secret Key Super Secret Key
    depends_on:
      - redis
      - rabbitmq

  identity-api:
    build:
      context: .
      dockerfile: ./Identity.API/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=database;Database=UserDb;User Id=sa;Password=Password123;TrustServerCertificate=True
      - Jwt__Secret=Super Secret Key Super Secret Key Super Secret Key Super Secret Key
    depends_on:
      - database

  ordering-api:
    build:
      context: .
      dockerfile: ./Ordering.API/Dockerfile
    environment:
      - RabbitMqConfig__Host=rabbitmq
      - RabbitMqConfig__Username=admin
      - RabbitMqConfig__Password=Password123
      - Jwt__Secret=Super Secret Key Super Secret Key Super Secret Key Super Secret Key
      - ConnectionStrings__DefaultConnection=Server=database;Database=OrderDb;User Id=sa;Password=Password123;TrustServerCertificate=True
    depends_on:
      - database
      - rabbitmq

volumes:
  cache:
  mssql-data:
  rabbitmq-log:
